#!/usr/bin/env python3
"""
Prometheus Metrics Format Demonstration

This script demonstrates the correct Prometheus exposition format
generated by metrics.py, showing all metric types and formats.

Author: Project Automata - Engineer Agent
Version: 1.0.0
Created: 2025-11-21
"""

import sys
import os
import time

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from skills.metrics import MetricsCollector


def main():
    print("=" * 80)
    print("PROMETHEUS METRICS FORMAT DEMONSTRATION")
    print("=" * 80)
    print()

    # Create metrics collector
    metrics = MetricsCollector("demo_app")

    print("Creating sample metrics...")
    print()

    # 1. COUNTER METRICS (automatically get _total suffix)
    print("1. Counter Metrics (requests, errors)")
    metrics.increment_counter(
        "http_requests",
        125,
        labels={"method": "GET", "endpoint": "/api/users", "status": "200"},
        help_text="Total number of HTTP requests",
    )
    metrics.increment_counter(
        "http_requests",
        42,
        labels={"method": "POST", "endpoint": "/api/users", "status": "201"},
        help_text="Total number of HTTP requests",
    )
    metrics.increment_counter(
        "http_requests",
        13,
        labels={"method": "GET", "endpoint": "/api/users", "status": "404"},
        help_text="Total number of HTTP requests",
    )

    # 2. GAUGE METRICS (instantaneous values)
    print("2. Gauge Metrics (current values)")
    metrics.set_gauge("active_connections", 42, help_text="Number of active connections")
    metrics.set_gauge("memory_usage_bytes", 1073741824, help_text="Memory usage in bytes")
    metrics.set_gauge("cpu_usage_percent", 65.5, help_text="CPU usage percentage")

    # 3. HISTOGRAM METRICS (distributions)
    print("3. Histogram Metrics (distributions)")

    # HTTP request duration (in seconds)
    for duration in [0.001, 0.005, 0.01, 0.015, 0.02, 0.05, 0.1, 0.15, 0.3, 0.5]:
        metrics.record_histogram(
            "http_request_duration_seconds",
            duration,
            labels={"endpoint": "/api/users"},
            buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
            help_text="HTTP request duration in seconds",
        )

    # Request size (in bytes) - custom buckets
    for size in [256, 512, 1024, 2048, 4096, 8192, 16384]:
        metrics.record_histogram(
            "http_request_size_bytes",
            size,
            labels={"method": "POST"},
            buckets=[512, 1024, 2048, 4096, 8192, 16384, 32768, 65536],
            help_text="HTTP request size in bytes",
        )

    # 4. TIMER METRICS (automatically use seconds and _seconds suffix)
    print("4. Timer Metrics (durations)")
    for i in range(10):
        start = metrics.start_timer("database_query")
        time.sleep(0.001 * (i + 1))  # Simulate varying query times
        metrics.stop_timer(
            "database_query",
            start,
            labels={"query_type": "SELECT"},
            help_text="Database query execution time",
        )

    # 5. METRICS WITH SPECIAL CHARACTERS (sanitized automatically)
    print("5. Metrics with special characters (auto-sanitized)")
    metrics.increment_counter(
        "workflow.execution.success",  # Dots replaced with underscores
        50,
        help_text="Successful workflow executions",
    )
    metrics.set_gauge(
        "queue-depth",  # Dashes replaced with underscores
        10,
        help_text="Current queue depth",
    )

    print()
    print("=" * 80)
    print("PROMETHEUS EXPOSITION FORMAT OUTPUT")
    print("=" * 80)
    print()

    # Export in Prometheus format
    output = metrics.export_prometheus()
    print(output)

    print()
    print("=" * 80)
    print("FORMAT VALIDATION")
    print("=" * 80)
    print()

    # Validate with prometheus_client parser
    try:
        from prometheus_client.parser import text_string_to_metric_families

        families = list(text_string_to_metric_families(output))

        print(f"✓ Successfully parsed {len(families)} metric families")
        print()
        print("Metric Summary:")
        print("-" * 40)

        for family in families:
            print(f"  • {family.name}")
            print(f"    Type: {family.type}")
            print(f"    Help: {family.documentation[:60]}...")
            if family.type == "histogram":
                print(f"    Samples: {len(family.samples)} (buckets + sum + count)")
            print()

        print("✓ All metrics conform to Prometheus specification!")
        print()

    except ImportError:
        print("⚠ prometheus_client not installed, skipping parser validation")
        print()
    except Exception as e:
        print(f"✗ Parser validation failed: {e}")
        print()
        return 1

    print("=" * 80)
    print("KEY FEATURES")
    print("=" * 80)
    print("""
✓ Metric Names:
  - Follow [a-zA-Z_:][a-zA-Z0-9_:]* pattern
  - Dots and dashes automatically converted to underscores
  - Counters automatically get _total suffix
  - Timers automatically get _seconds suffix

✓ Label Names:
  - Follow [a-zA-Z_][a-zA-Z0-9_]* pattern
  - Sorted alphabetically in output
  - Properly quoted values

✓ Histogram Format:
  - Includes _bucket{le="<value>"} for each bucket
  - Includes _bucket{le="+Inf"} for total count
  - Includes _sum for total sum of values
  - Includes _count for total number of observations
  - Cumulative bucket counts

✓ Counter Format:
  - Single value line
  - Automatically adds _total suffix

✓ Gauge Format:
  - Single value line
  - Represents current state

✓ Metadata:
  - # HELP lines for all metrics
  - # TYPE lines for all metrics
  - Proper spacing between metric families
    """)

    return 0


if __name__ == "__main__":
    sys.exit(main())
